name: Bug report
description: Report a problem
title: "[Bug]: "
labels: [ "bug" ]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened?
    validations:
      required: true