name: Build JSON to gh-pages

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"  # daily 03:00 UTC

permissions:
  contents: write

jobs:
  build-and-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-pages
        uses: actions/checkout@v5
        with:
          ref: gh-pages
          path: gh-pages

      - name: Checkout master (code)
        uses: actions/checkout@v5
        with:
          ref: master
          path: master

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Install deps
        working-directory: master
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build JSON files into gh-pages
        run: |
          python master/src/fetch_device_data.py --scores-output gh-pages/devices_with_scores.json --generate-rubric --rubric-output gh-pages/rubric.json

      - name: Commit to gh-pages if changed
        working-directory: gh-pages
        run: |
          set -e
          # Stage the files (works for both new and modified files)
          git add devices_with_scores.json rubric.json || true
          # Initialize commit message parts
          changed_files=()
          # Check if devices_with_scores.json has changes
          if ! git diff --cached --quiet -- devices_with_scores.json 2>/dev/null; then
            changed_files+=("devices_with_scores.json")
          fi
          # Check if rubric.json has changes
          if ! git diff --cached --quiet -- rubric.json 2>/dev/null; then
            changed_files+=("rubric.json")
          fi
          # Commit only if there are changes
          if [ ${#changed_files[@]} -gt 0 ]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            ts=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
            # Construct commit message based on changed files
            if [ ${#changed_files[@]} -eq 1 ]; then
              commit_msg="chore(gh-pages): update ${changed_files[0]} ${ts}"
            else
              commit_msg="chore(gh-pages): update ${changed_files[0]} and ${changed_files[1]} ${ts}"
            fi
            git commit -m "$commit_msg"
            git push
          else
            echo "No changes to commit."
          fi
