name: Build JSON to gh-pages

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"  # daily 03:00 UTC

permissions:
  contents: write

jobs:
  build-and-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-pages
        uses: actions/checkout@v5
        with:
          ref: gh-pages
          path: gh-pages

      - name: Checkout master (code)
        uses: actions/checkout@v5
        with:
          ref: master
          path: master

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Install deps
        working-directory: master
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build devices_with_scores.json into gh-pages
        run: |
          python master/src/fetch_device_data.py --scores-output gh-pages/devices_with_scores.json

      - name: Commit to gh-pages if changed
        working-directory: gh-pages
        run: |
          set -e
          # Stage the file (works for both new and modified files)
          git add devices_with_scores.json || true
          # Commit only if something is staged
          if ! git diff --cached --quiet -- devices_with_scores.json; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            ts=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
            git commit -m "chore(gh-pages): update devices_with_scores.json ${ts}"
            git push
          else
            echo "No changes to commit."
          fi
